{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $cr := index .Values "kubetail" "clusterRole" -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $cr.name | default (include "kubetail.fullname" .) }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $cr.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $cr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["", apps, batch]
  resources: [cronjobs, daemonsets, deployments, jobs, namespaces, nodes, pods, pods/log, replicasets, statefulsets]
  verbs: [get, list, watch]
{{- end }}
