{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $cr := index .Values "kubetail" "clusterRole" -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $cr.name | default (include "kubetail.fullname" .) }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $cr.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kubetail.annotations" . | nindent 4 }}
    {{- with $cr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
{{- with $cr.rules }}
{{- toYaml . | nindent 0 }}
{{- end }}
{{- end }}
