kind: ConfigMap
apiVersion: v1
metadata:
  {{- include "kubetail.metadataNamespace" $ | nindent 2 }}
  name: {{ include "kubetail.configMapName" . }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
data:
  config.yaml: |
    {{- include "kubetail.config" $ | nindent 4 }}

