kind: ConfigMap
apiVersion: v1
metadata:
  {{- include "kubetail.metadataNamespace" $ | nindent 2 }}
  name: {{ include "kubetail.configMapName" . }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
data:
  config.yaml: |
    addr: :{{ .Values.deployment.containerPort }}
    auth-mode: {{ .Values.authMode }}
{{- with .Values.config }}
{{ toYaml . | indent 4 }}
{{- end }}
