{{- $dep := index .Values "kubetail" "deployment" -}}
{{- $podTmpl := index .Values "kubetail" "podTemplate" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ default (include "kubetail.fullname" .) $dep.name }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $dep.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kubetail.annotations" . | nindent 4 }}
    {{- with $dep.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $dep.replicas }}
  revisionHistoryLimit: {{ $dep.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "kubetail.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml $dep.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "kubetail.labels" . | nindent 8 }}
        {{- with $podTmpl.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include "kubetail.config" . | sha256sum }}
        {{- include "kubetail.annotations" . | nindent 8 }}
        {{- with $podTmpl.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ $podTmpl.automountServiceAccountToken }}
      {{- if eq .Values.kubetail.authMode "cluster" }}
      serviceAccountName: {{ include "kubetail.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml $podTmpl.securityContext | nindent 8 }}
      containers:
      - name: kubetail
        image: {{ include "kubetail.image" . }}
        securityContext:
          {{- toYaml $podTmpl.containerSecurityContext | nindent 10 }}
        imagePullPolicy: {{ .Values.kubetail.image.pullPolicy }}
        ports:
        - name: kubetail
          protocol: TCP
