kind: Deployment
apiVersion: apps/v1
metadata:
  {{- include "kubetail.metadataNamespace" $ | nindent 2 }}
  name: {{ if .Values.deployment.name }}{{ .Values.deployment.name }}{{ else }}{{ include "kubetail.fullname" . }}{{ end }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubetail.selectorLabels" $ | nindent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        {{- include "kubetail.labels" $ | nindent 8 }}
      annotations:
        checksum/config: {{ include "kubetail.config" . | sha256sum }}
        {{- with .Values.deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken }}
      {{- if eq .Values.authMode "cluster" }}
      serviceAccountName: {{ include "kubetail.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:
      - name: kubetail
        image: {{ .Values.image.registry }}:{{ default .Chart.AppVersion .Values.image.tag }}
        securityContext:
          {{- toYaml .Values.deployment.securityContext | nindent 10 }}
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        ports:
        - name: kubetail
          protocol: TCP
          containerPort: {{ .Values.deployment.containerPort }}
        args:
        {{- range .Values.deployment.args }}
        - {{ . }}
        {{- end }}
        {{- if .Values.deployment.livenessProbe.enabled }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml (omit . "enabled") | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe.enabled }}
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml (omit . "enabled") | nindent 10 }}
        {{- end }}
        {{- end }}
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "kubetail.configMapName" . }}
