{{- $ing := index .Values "ingress" -}}
{{- if $ing.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ if $ing.name }}{{ $ing.name }}{{ else }}{{ include "kubetail.fullname" . }}{{ end }}
  annotations:
{{- with $ing.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range $ing.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ if $.Values.service.name }}{{ $.Values.service.name }}{{ else }}{{ include "kubetail.fullname" $ }}{{ end }}
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
  {{- end }}
  {{- with $ing.tls }}
  tls:
  {{- range . }}
  - hosts:
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ if $ing.secretName }}{{ $ing.secretName }}{{ else }}{{ include "kubetail.fullname" $ }}{{ end }}
  {{- end }}
  {{- end }}
{{- end }}
