{{- if eq .Values.kubetail.authMode "cluster" }}
{{- $r := index .Values "kubetail" "role" -}}
{{- $rb := index .Values "kubetail" "roleBinding" -}}
{{- range .Values.kubetail.allowedNamespaces }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ . }}
  name: {{ $rb.name | default (include "kubetail.fullname" $) }}
  labels:
    {{- include "kubetail.labels" $ | nindent 4 }}
    {{- with $rb.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $rb.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubetail.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $r.name | default (include "kubetail.fullname" $) }}
---
{{- end }}
{{- end }}
