{{- $svc := index .Values "kubetail" "service" -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "kubetail.serviceName" . }}
  namespace: {{ include "kubetail.namespace" . }}
  labels:
    {{- include "kubetail.labels" . | nindent 4 }}
    {{- with $svc.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with $svc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubetail.selectorLabels" . | nindent 4 }}
  ports:
  - name: kubetail
    protocol: TCP
    port: {{ $svc.port }}
    targetPort: kubetail
    appProtocol: http
