# Default values for kubetail chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Overrides the chart's name
nameOverride: null

# -- Override the chart's computed fullname
fullnameOverride: null

# -- Override the release's namespace
namespaceOverride: null

# ###########################################################################################
#
# Base config for kubetail app including kubernetes configurations
#
# ###########################################################################################

kubetail:
  # -- Auth mode lets you specify kubetail's authentication mode
  # There are 3 options:
  # - cluster: Use's cluster RBAC
  # - token: Use's user-provided token
  # - local: Uses local kubectl config
  authMode: cluster
  # -- Common annotations for all kubernetes resources
  annotations:
    keyA1: valA1
    keyA2: valA2
  # -- Common labels for all kubernetes resources
  labels:
    keyA1: valA1
    keyA2: valA2

  # -- config file contents (see https://github.com/kubetail-org/kubetail for defaults)
  config: |
    session:
      secret: ${KUBETAIL_CSRF_SECRET}
    csrf:
      secret: ${KUBETAIL_SESSION_SECRET}

  secret:
    # If true, add Secret resource with configured values
    enabled: true
    # -- Overrides the Secret resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations:
      keyB1: valB1
      keyB2: valB2
    # -- Additional labels
    labels:
      keyB1: valB1
      keyB2: valB2
    # -- base64-encoded secret value for csrf (will be autogenerated if null)
    KUBETAIL_CSRF_SECRET: null
    # -- base64-encoded secret value for session (will be autogenerated if null)
    KUBETAIL_SESSION_SECRET: null

  image:
    # -- Image registry
    registry: docker.io
    # -- Image repository
    repository: kubetail/kubetail
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: null
    # -- Overrides the image tag with an image digest
    digest: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent

  podTemplate:
    # -- Additional annotations
    annotations:
      keyC1: valC1
      keyC2: valC2
    # -- Additional labels
    labels:
      keyC1: valC1
      keyC2: valC2
    # -- Affinity for pods
    affinity: {}
    # -- AutomountServiceAccounttoken for pods
    automountServiceAccountToken: true
    # -- Additional env
    env: {}
    # -- Additional envFrom
    envFrom: {}
    # -- Additional args
    args:
    - key=val
    # -- Port number
    port: 4000
    # -- Liveness probe
    livenessProbe:
      httpGet:
        scheme: HTTP
        path: /healthz
        port: kubetail
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    # -- Readiness probe
    readinessProbe:
      httpGet:
        scheme: HTTP
        path: /healthz
        port: kubetail
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    # -- Resources
    resources: {}
    # -- Security context
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    # -- Kubetail container's security context
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true

  clusterRole:
    # -- Overrides the ClusterRole resource name whose default is the chart's computed fullname
    name: xxx
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- Rules
    rules:
    - apiGroups: ["", apps, batch]
      resources: [cronjobs, daemonsets, jobs, namespaces, nodes, pods, pods/log, replicasets, statefulsets]
      verbs: [get, list, watch]
  
  clusterRoleBinding:
    # -- Overrides the ClusterRoleBinding resource name whose default is the chart's computed fullname
    name: xxx
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}

  configMap:
    # -- Overrides the ConfigMap resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations:
      keyB1: keyB1
      keyB2: keyB2
    # -- Additional labels
    labels:
      keyB1: keyB1
      keyB2: keyB2

  deployment:
    # -- Overrides the Deployment resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations:
      keyB1: valB1
      keyB2: valB2
    # -- Additional labels
    labels:
      keyB1: valB1
      keyB2: valB2
    # -- Replicas
    replicas: 1
    # -- Revision history limit
    revisionHistoryLimit: 5
    # -- Strategy
    strategy:
      type: RollingUpdate
    # -- PriorityClassName
    priorityClassName: null
    # -- Node selector
    nodeSelector: {}
    # -- Affinity
    affinity: {}
    # -- Tolerations
    tolerations: []

  service:
    # -- Overrides the Service resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- Port
    port: 4000
    # -- Type
    type: ClusterIP

  serviceAccount:
    # -- Overrides the Service resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- AutomountServiceAccountToken
    automountServiceAccountToken: true

  ingress:
    # If true, adds Ingress resource
    enabled: false
    # -- Overrides the ClusterRole resource name whose default is the chart's computed fullname
    name: null
    # -- Additional annotations
    annotations: {}
    # -- Additional labels
    labels: {}
    # -- Hosts
    hosts: []
    # -- TLS
    tls: []
