# Default values for kubetail.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# override name of the chart
nameOverride:

# override full name of the chart+release
fullnameOverride:

# override the namespace that resources are installed into
namespaceOverride:

# kubetail auth-mode
authMode: cluster

# labels to apply to all resources deployed by the chart
labels: {}

# image options
image:
  registry: kubetail/kubetail
  tag:
  pullPolicy:

# cluster-role options
clusterRole:
  name:

# cluster-role-binding options
clusterRoleBinding:
  name:
  rules:
  - apiGroups:
    - ""
    - apps
    - batch
    resources:
    - cronjobs
    - daemonsets
    - deployments
    - jobs
    - namespaces
    - nodes
    - pods
    - pods/log
    - replicasets
    - statefulsets
    verbs:
    - get
    - list
    - watch

# configMap options
configMap:
  name:

# deployment options
deployment:
  name:
  replicas: 1
  revisionHistoryLimit: 10
  updateStrategy: {}
  containerPort: 4000
  args:
  - --config=/etc/kubetail/config.yaml
  livenessProbe:
    httpGet:
      scheme: HTTP
      path: /healthz
      port: 4000
    initialDelaySeconds: 30
    timeoutSeconds: 30
    periodSeconds: 10
    failureThreshold: 3
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

# service options
service:
  name:
  type: ClusterIP
  port: 4000

# service-account options
serviceAccount:
  name:

# ingress options
ingress:
  enabled: false
  annotations: {}

# kubetail config (see https://github.com/kubetail-org/kubetail for defaults)
config:
  session:
    secret: REPLACEME
  csrf:
    secret: REPLACEME

